export const LOADING = "LOADING";

export const REGISTER_USER = "REGISTER_USER";
export const LOGIN_USER = "LOGIN_USER";
export const GET_AUTH_USER = "GET_AUTH_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const LOAD_USER = "LOAD_USER";

export const REGISTER_ERROR = "REGISTER_ERROR"
export const LOGIN_ERROR = "LOGIN_ERROR"
export const LOAD_USER_ERROR = "LOAD_USER_ERROR"

export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const RESET_PASSWORD = "RESET_PASSWORD";

export const FORGOT_PASSWORD_ERROR = "FORGOT_PASSWORD_ERROR"
export const RESET_PASSWORD_ERROR = "RESET_PASSWORD_ERROR"

export const ADD_AVATAR = "ADD_AVATAR";
export const REMOVE_AVATAR = "REMOVE_AVATAR";

export const ADD_AVATAR_ERROR = "ADD_AVATAR_ERROR"
export const RENOVE_AVATAR_ERROR = "REMOVE_AVATAR_ERROR"

export const ADD_PROFILE_BIO = "ADD_PROFILE_BIO";
export const EDIT_PROFILE_BIO = "EDIT_PROFILE_BIO";

export const ADD_PROFILE_BIO_ERROR = "ADD_PROFILE_BIO_ERROR"
export const EDIT_PROFILE_BIO_ERROR = "EDIT_PROFILE_BIO_ERROR"

export const ADD_SOCIAL_LINK = "ADD_SOCIAL_LINK";
export const REMOVE_SOCIAL_LINK = "REMOVE_SOCIAL_LINK";
export const EDIT_SOCIAL_LINK = "EDIT_SOCIAL_LINK";

export const ADD_SOCIAL_LINK_ERROR = "ADD_SOCIAL_LINK_ERROR"
export const REMOVE_SOCIAL_LINK_ERROR = "REMOVE_SOCIAL_LINK_ERROR"
export const EDIT_SOCIAL_LINK_ERROR = "EDIT_SOCIAL_LINK_ERROR"


